[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps",
  "npx prisma generate"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"
