[phases.setup]
nixPkgs = [
  "nodePackages_latest.nodejs",
  "yarn"
]

[phases.install]
cmds = [
  "node -v",
  "which node",
  "yarn --version",
  "yarn install --frozen-lockfile",
]

[start]
cmd = "yarn start"
