[phases.setup]
nixPkgs = [
  "nodePackages_latest.nodejs",
  "pnpm"
]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile",
  "pnpm prisma generate",
  "pnpm run migrate"
]

[start]
cmd = "pnpm run start"
